---
title: "3.1 - RAD_Genomics_BootCamp"
author: "William Shropshire"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/RAD_genomics_workshop")
```

## Traditional 'OG' Epidemiology 

The first exercise utilizes a dataset from HistData  
```{r download packages, echo = FALSE}
# Download the package manager tool 'pacman' if not in user environment, otherwise ignore
if (!requireNamespace("pacman", quietly = TRUE)) {
  install.packages("pacman")
}

pacman::p_load(
  HistData,
  tidyverse,
  lubridate
)
```

## What if John Snow had 'R'? 

```{r John Snow 1854 London cholera death outbreak data, echo=FALSE}
data(Snow.dates)

head(Snow.dates)
Snow.dates$clr <- ifelse(Snow.dates$date < mdy("09/08/1854"), "red", "darkgreen")

## Plot deaths over time
ggplot(Snow.dates, aes(x = date, y = deaths, color = clr)) +
  geom_line(size = 2) +
  geom_point(size = 3, shape = 16) +
  geom_text(aes(x = mdy("09/08/1854"), y = 40, label = "Pump handle\nremoved Sept. 8"), vjust = -1, hjust = -0.25) +
  geom_vline(xintercept = mdy("09/08/1854"), linetype = "dotted", color = "red", size = 1) +  # Adding a vertical dotted line
  scale_color_manual(values = c("red", "darkgreen"), breaks = c("red", "darkgreen"), labels = c("Intact", "Removed")) +
  labs(title = "Cholera Deaths Over Time",
       x = "Date",
       y = "Number of Deaths",
       color = "Pump Status") +
  theme_minimal()

ggsave("cholera_deaths_time.pdf")
```

# What if John Snow had (1) knowledge of germ theory; (2) capacity to culture Vibrio cholera; (3) either phenotypic or genotypic data at his disposal?

```{r fictional 1854 Cholera outbreak dataset, echo=FALSE}
df1<- read.csv("~/Documents/RAD_genomics_workshop/cholera_fictional_data.csv")

# Create a histogram without serotyping data
ggplot(df1, aes(x = as.Date(date))) +
  geom_bar(aes(y = count), stat = "identity") +
  geom_line(aes(y = deaths, color = "Deaths"), linetype = "dotted", size = 1.5) +
  labs(title = "Histogram of Cholera Episodes Over Time",
       x = "Date",
       y = "Cholera Episodes") +
  scale_color_manual(values = "red", name = "Mortality") +
  theme_minimal()

ggsave("fictional_hist_wo_serotype.pdf")

# Check for correlation between deaths and serotype
corr_test <- chisq.test(table(df1$deaths, df1$count))
print(corr_test)

# Convert 'date' column to Date format
df1$date <- as.Date(df1$date)

# Create a histogram with serotyping data
ggplot(df1, aes(x = date)) +
  geom_bar(aes(y = count, fill = serotype), stat = "identity") +
  geom_line(aes(y = deaths, color = "Deaths"), linetype = "dotted", size = 1.5) +
  labs(title = "Histogram of Cholera Episodes Over Time by Serotype",
       x = "Date",
       y = "Cholera Episodes") +
  scale_color_manual(values = "red", name = "Mortality") +
  scale_fill_manual(values = c("O1" = "blue", "non-O1" = "green"), name = "Serotype") +
  geom_text(aes(x = as.Date("1855-12-01"), y = max(count), 
                label = "Chi-squared p-value: 0.003"),
            hjust = 1, vjust = 1, size = 4, color = "black") +
  theme_minimal()

ggsave("fictional_hist_w_serotype.pdf")
```

```{r clean up, echo=FALSE}
# Clear data
rm(list = ls())  

# Clear packages
detach("package:datasets", unload = T)  
p_unload(all)  

# Clear plots
graphics.off()  

# Clear console
cat("\014") 
```
